# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
before_install:
  - bundle install

cache:
  - bundler
  - cocoapods

osx_image: xcode7.3
language: objective-c
xcode_workspace: Example/SwiftyImageIO.xcworkspace
xcode_scheme: SwiftyImageIO-Example
podfile: Example/Podfile

script:
- set -o pipefail && xcodebuild test -workspace Example/SwiftyImageIO.xcworkspace -scheme SwiftyImageIO-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
